//! Backend layer: the GUI is a pure daemon client.
//!
//! This starts and connects to the `nanna-daemon` sidecar and forwards every
//! high-level call to [`DaemonClient`]. There is no in-process fallback: if the
//! daemon cannot be reached the app reports a disconnected status (the frontend
//! surfaces a "start the daemon" affordance) rather than silently running an
//! embedded copy of the whole stack.
//!
//! Most of the API surface is near-identical proxy methods that forward to
//! [`DaemonClient`]; those are generated by the [`daemon_proxies!`] macro at the
//! bottom of this file. Only methods with distinct result mapping (init, status,
//! event forwarding) are hand-written.

use crate::daemon_client::{DaemonClient, DaemonClientConfig, DaemonEvent};
use crate::daemon_manager::{DaemonManager, DaemonManagerConfig};
use crate::AppState;
use serde::Serialize;
use serde_json::Value;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use tauri::{AppHandle, Emitter, Manager};
use tokio::sync::{broadcast, RwLock};
use tracing::{error, info, warn};

/// Backend mode reported to the frontend.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum BackendMode {
    /// Connected to the daemon sidecar.
    Daemon,
    /// Daemon unreachable — the app cannot serve requests until it connects.
    Disconnected,
}

/// Backend status for frontend
#[derive(Debug, Clone, Serialize)]
pub struct BackendStatus {
    pub mode: BackendMode,
    pub connected: bool,
    pub daemon_url: Option<String>,
    pub daemon_state: String,
    pub version: String,
}

/// The unified backend interface (daemon client + sidecar lifecycle).
pub struct Backend {
    daemon_manager: Arc<DaemonManager>,
    daemon_client: Arc<DaemonClient>,
    app: Arc<RwLock<Option<AppHandle>>>,
    /// Prevents concurrent init attempts.
    initializing: Arc<RwLock<bool>>,
    /// Ensures the single DaemonEvent→Tauri forwarding task starts exactly once.
    forwarding_started: Arc<AtomicBool>,
}

impl Backend {
    /// Create a new backend.
    pub fn new() -> Self {
        let manager_config = DaemonManagerConfig::default();
        let client_config = DaemonClientConfig {
            url: format!("ws://{}:{}", manager_config.host, manager_config.port),
            ..Default::default()
        };

        Self {
            daemon_manager: Arc::new(DaemonManager::new(manager_config)),
            daemon_client: Arc::new(DaemonClient::new(client_config)),
            app: Arc::new(RwLock::new(None)),
            initializing: Arc::new(RwLock::new(false)),
            forwarding_started: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Sender side of the shared [`DaemonEvent`] bus. The WebSocket client
    /// publishes deserialized daemon events here; [`Backend::start_event_forwarding`]
    /// is the single place that translates them into Tauri window events.
    pub fn daemon_event_sender(&self) -> broadcast::Sender<DaemonEvent> {
        self.daemon_client.event_sender()
    }

    /// Set the app handle (required for sidecar and event emission)
    pub async fn set_app(&self, app: AppHandle) {
        *self.app.write().await = Some(app);
    }

    /// Initialize the backend: start the daemon sidecar, connect the client,
    /// and begin health monitoring + event forwarding.
    ///
    /// On failure this returns [`BackendMode::Disconnected`] rather than falling
    /// back to an embedded backend. The daemon client's auto-reconnect keeps
    /// trying, so a daemon that starts late will still attach.
    pub async fn init(&self, app: &AppHandle) -> BackendMode {
        // Already connected?
        if self.daemon_client.is_connected().await {
            info!("Backend already connected to daemon");
            return BackendMode::Daemon;
        }

        // Serialize concurrent init attempts.
        {
            let mut initializing = self.initializing.write().await;
            if *initializing {
                info!("Backend initialization already in progress, waiting...");
                drop(initializing);
                loop {
                    tokio::time::sleep(tokio::time::Duration::from_millis(100)).await;
                    if !*self.initializing.read().await {
                        return if self.daemon_client.is_connected().await {
                            BackendMode::Daemon
                        } else {
                            BackendMode::Disconnected
                        };
                    }
                }
            }
            *initializing = true;
        }

        info!("Initializing backend (daemon-only)...");
        *self.app.write().await = Some(app.clone());

        // Start the single event-forwarding task (idempotent).
        self.start_event_forwarding(app.clone());

        // Start the daemon sidecar, then connect the client.
        let result = match self.daemon_manager.start(app).await {
            Ok(()) => {
                info!("Daemon sidecar started");
                match self.daemon_client.connect().await {
                    Ok(()) => {
                        info!("Backend: connected to daemon");
                        self.daemon_manager.clone().start_health_monitor(app.clone());
                        BackendMode::Daemon
                    }
                    Err(e) => {
                        error!("Daemon started but client connection failed: {e}");
                        BackendMode::Disconnected
                    }
                }
            }
            Err(e) => {
                error!("Failed to start daemon sidecar: {e}");
                BackendMode::Disconnected
            }
        };

        *self.initializing.write().await = false;
        result
    }

    /// Shutdown the backend (stop the daemon sidecar).
    pub async fn shutdown(&self) {
        info!("Shutting down backend...");
        self.daemon_client.disconnect();
        if let Err(e) = self.daemon_manager.stop().await {
            warn!("Error stopping daemon: {e}");
        }
    }

    /// Get backend status.
    pub async fn status(&self) -> BackendStatus {
        let daemon_state = self.daemon_manager.state().await;
        let connected = self.daemon_client.is_connected().await;

        BackendStatus {
            mode: if connected {
                BackendMode::Daemon
            } else {
                BackendMode::Disconnected
            },
            connected,
            daemon_url: connected.then(|| self.daemon_manager.ws_url()),
            daemon_state: format!("{daemon_state:?}").to_lowercase(),
            version: env!("CARGO_PKG_VERSION").to_string(),
        }
    }

    /// Whether the daemon client is currently connected.
    pub async fn is_connected(&self) -> bool {
        self.daemon_client.is_connected().await
    }

    /// Send a raw request to the daemon.
    pub async fn daemon_request(&self, action: Value) -> Result<Value, String> {
        self.daemon_client.request(action).await
    }

    /// Start forwarding daemon events to Tauri. This is the ONLY
    /// `DaemonEvent` → Tauri translation path.
    fn start_event_forwarding(&self, app: AppHandle) {
        // Guard against double-start (init can run more than once).
        if self.forwarding_started.swap(true, Ordering::SeqCst) {
            return;
        }
        let mut events = self.daemon_client.subscribe_events();

        tokio::spawn(async move {
            loop {
                let event = match events.recv().await {
                    Ok(event) => event,
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                        warn!("Event forwarding lagged, dropped {} events", n);
                        continue;
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
                };
                match &event {
                    DaemonEvent::MessageDelta { session_id, delta, .. } => {
                        let _ = app.emit("stream-chunk", serde_json::json!({
                            "session_id": session_id,
                            "chunk": delta,
                            "done": false,
                        }));
                    }
                    DaemonEvent::MessageEnd { session_id, .. } => {
                        let _ = app.emit("stream-chunk", serde_json::json!({
                            "session_id": session_id,
                            "chunk": "",
                            "done": true,
                        }));
                    }
                    DaemonEvent::ThinkingDelta { session_id, delta, .. } => {
                        let _ = app.emit("thinking-chunk", serde_json::json!({
                            "session_id": session_id,
                            "delta": delta,
                        }));
                    }
                    DaemonEvent::ToolStart { session_id, call_id, name, input, model, tokens, total_tokens } => {
                        let mut tool_call = serde_json::json!({
                            "id": call_id,
                            "name": name,
                            "input": input,
                            "output": "",
                            "success": false,
                            "duration_ms": 0,
                        });
                        if let Some(m) = &model {
                            tool_call["model"] = serde_json::json!(m);
                        }
                        if let Some(t) = tokens {
                            tool_call["tokens"] = serde_json::json!(t);
                        }
                        if let Some(t) = total_tokens {
                            tool_call["total_tokens"] = serde_json::json!(t);
                        }
                        let _ = app.emit("tool-call", serde_json::json!({
                            "session_id": session_id,
                            "tool_call": tool_call,
                            "status": "started",
                        }));
                    }
                    DaemonEvent::ToolEnd { session_id, call_id, output, success, duration_ms, data } => {
                        let mut tool_call = serde_json::json!({
                            "id": call_id,
                            "output": output,
                            "success": success,
                            "duration_ms": duration_ms.unwrap_or(0),
                        });
                        if let Some(d) = data {
                            tool_call["data"] = d.clone();
                        }
                        let _ = app.emit("tool-call", serde_json::json!({
                            "session_id": session_id,
                            "tool_call": tool_call,
                            "status": if *success { "completed" } else { "error" },
                        }));
                    }
                    DaemonEvent::ModelSwitch { model, reason } => {
                        // Keep AppState's active_model in sync so get_model_status agrees.
                        if let Some(state) = app.try_state::<Arc<RwLock<AppState>>>() {
                            let state_guard = state.read().await;
                            let mut active = state_guard.active_model.write().await;
                            *active = model.clone();
                        }
                        let _ = app.emit("model-status", serde_json::json!({
                            "active_model": model,
                            "fallback_reason": reason,
                            "rate_limited_models": [],
                        }));
                    }
                    DaemonEvent::Error { code, message, session_id } => {
                        let _ = app.emit("error", serde_json::json!({
                            "code": code,
                            "message": message,
                            "session_id": session_id,
                        }));
                    }
                    DaemonEvent::TaskRunStarted { scope, scope_id, goal } => {
                        let _ = app.emit("task-event", serde_json::json!({
                            "kind": "run_started",
                            "scope": scope,
                            "scope_id": scope_id,
                            "goal": goal,
                        }));
                    }
                    DaemonEvent::TaskRunProgress { scope, scope_id, task_id, kind, detail } => {
                        // The daemon's own `kind` (started/completed/replanned/...)
                        // is forwarded as `progress_kind`; the payload's `kind` is
                        // the task-event discriminator.
                        let _ = app.emit("task-event", serde_json::json!({
                            "kind": "run_progress",
                            "scope": scope,
                            "scope_id": scope_id,
                            "task_id": task_id,
                            "progress_kind": kind,
                            "detail": detail,
                        }));
                    }
                    DaemonEvent::TaskRunCompleted { scope, scope_id, report } => {
                        let _ = app.emit("task-event", serde_json::json!({
                            "kind": "run_completed",
                            "scope": scope,
                            "scope_id": scope_id,
                            "report": report,
                        }));
                    }
                    _ => {}
                }
            }
        });
    }

    // =========================================================================
    // High-level API with distinct result mapping (hand-written).
    // =========================================================================

    /// Cancel an active chat.
    pub async fn chat_cancel(&self, session_id: &str) -> Result<bool, String> {
        let val = self.daemon_client.chat_cancel(session_id).await?;
        Ok(val.get("status").and_then(|s| s.as_str()) == Some("cancelled"))
    }

    /// Get daemon logs.
    pub async fn get_logs(&self, limit: Option<usize>) -> Result<Vec<Value>, String> {
        let val = self.daemon_client.system_logs(limit).await?;
        Ok(val
            .get("logs")
            .and_then(|l| l.as_array())
            .cloned()
            .unwrap_or_default())
    }

    /// Get system status.
    pub async fn system_status(&self) -> Result<Value, String> {
        self.daemon_client.system_status().await
    }
}

/// Generates the daemon proxy methods on [`Backend`].
///
/// Each table entry expands to an unconditional forward:
///
/// ```ignore
/// pub async fn name(&self, args...) -> Result<Value, String> {
///     self.daemon_client.name(args...).await   // identically named method
/// }
/// ```
macro_rules! daemon_proxies {
    (
        $(
            $(#[$meta:meta])*
            $name:ident ( $( $arg:ident : $ty:ty ),* $(,)? );
        )*
    ) => {
        impl Backend {
            $(
                $(#[$meta])*
                pub async fn $name(&self $(, $arg: $ty )* ) -> Result<Value, String> {
                    self.daemon_client.$name( $( $arg ),* ).await
                }
            )*
        }
    };
}

daemon_proxies! {
    // --- Chat ---
    /// Send a chat message
    chat_send(session_id: &str, content: &str, attachments: Vec<serde_json::Value>);

    // --- Session management ---
    /// List sessions
    sessions_list();
    /// List sessions filtered by workspace
    sessions_list_by_workspace(workspace_id: Option<&str>);
    /// Create a session
    session_create(name: Option<&str>);
    /// Create a session in a specific workspace
    session_create_in_workspace(name: Option<&str>, workspace_id: Option<&str>);
    /// Set or clear the workspace for a session
    session_set_workspace(session_id: &str, workspace_id: Option<&str>);
    /// Get session history
    session_history(session_id: &str, limit: Option<usize>);
    /// Delete a session
    session_delete(session_id: &str);
    /// Delete all sessions
    sessions_delete_all();
    /// Rename a session
    session_rename(session_id: &str, name: &str);
    /// Get session run state (in-flight streaming text, active tools).
    /// `light` skips the run journal — for periodic counter polls.
    session_get_run_state(session_id: &str, light: bool);
    /// Clear session history
    session_clear(session_id: &str);

    // --- Memory operations ---
    /// List all memories
    memory_list(scope: Option<&str>);
    /// Search memories
    memory_search(query: &str, limit: Option<usize>);
    /// Get a specific memory
    memory_get(id: &str);
    /// Create a memory
    memory_create(content: &str, tags: Option<Vec<String>>, importance: Option<u8>);
    /// Update a memory
    memory_update(id: &str, content: Option<&str>, tags: Option<Vec<String>>);
    /// Delete a memory
    memory_delete(id: &str);
    /// Clear all memories
    memory_clear();
    /// Get memory stats
    memory_stats();
    /// Trigger memory consolidation
    memory_consolidate();

    // --- Scheduler operations ---
    /// List scheduled jobs
    scheduler_list();
    /// Get job details
    scheduler_get(id: &str);
    /// Add a cron job
    scheduler_add(schedule: &str, task: &str, name: Option<&str>);
    /// Update a job
    scheduler_update(id: &str, schedule: Option<&str>, task: Option<&str>, enabled: Option<bool>);
    /// Remove a job
    scheduler_remove(id: &str);
    /// Run a job immediately
    scheduler_run_now(id: &str);
    /// Get job history
    scheduler_history(id: &str, limit: Option<usize>);

    // --- Tool operations ---
    /// List all tools
    tool_list();
    /// Execute a tool
    tool_execute(name: &str, input: Value);
    /// Create a user tool
    tool_create(name: &str, description: &str, code: &str, needs_shell: Option<bool>);
    /// Update a user tool
    tool_update(name: &str, description: Option<&str>, code: Option<&str>, needs_shell: Option<bool>);
    /// Delete a user tool
    tool_delete(name: &str);
    /// Test a user tool
    tool_test(code: &str, input: Value);
    /// List user tools
    tool_list_user();
    /// Get tool source code
    tool_get_source(name: &str);

    // --- Config operations ---
    /// Get config (full or by path)
    config_get(path: Option<&str>);
    /// Set config value
    config_set(path: &str, value: Value);
    /// Reset config
    config_reset(path: Option<&str>);
    /// Reload config from disk
    config_reload();
    /// Export config
    config_export();
    /// Import config
    config_import(config: Value);

    // --- Workspace operations ---
    /// List workspaces
    workspace_list();
    /// Get workspace details
    workspace_get(id: &str);
    /// Open/register a workspace
    workspace_open(path: &str);
    /// Close/unregister a workspace
    workspace_close(id: &str);
    /// Set active workspace
    workspace_set_active(id: &str);
    /// Clear active workspace (global mode)
    workspace_clear_active();
    /// Reload workspace context
    workspace_reload(id: &str);
    /// Get workspace context
    workspace_get_context(id: &str);
    /// Update workspace context file
    workspace_update_context(id: &str, file: &str, content: &str);

    // --- Channel operations ---
    /// List channels
    channel_list();
    /// Get channel status
    channel_status(id: Option<&str>);

    // --- Task operations ---
    /// List tasks in a scope
    task_list(scope: &str, session_id: Option<&str>, include_closed: Option<bool>);
    /// Get one task with notes + activity
    task_get(id: i64);
    /// Create a task (pass-through payload)
    task_create(payload: Value);
    /// Partially update a task
    task_update(id: i64, patch: Value);
    /// Complete a task (with acceptance verification)
    task_done(id: i64, workdir: Option<&str>);
    /// Delete a task subtree
    task_delete(id: i64);
    /// Append a working note to a task
    task_note(id: i64, content: &str);
    /// Filter-language query over a scope's tasks
    task_query(filter: &str, scope: &str, session_id: Option<&str>);
    /// Start a long-horizon run (pass-through payload)
    task_start_run(payload: Value);
    /// Status of the scope's run
    task_run_status(scope: &str, session_id: Option<&str>);
    /// Cancel the scope's active run
    task_cancel_run(scope: &str, session_id: Option<&str>);
}

impl Default for Backend {
    fn default() -> Self {
        Self::new()
    }
}
