import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'

/**
 * Guards against components referenced in templates under a name Nuxt never registers.
 *
 * Vue does not fail on an unresolvable component — it logs a `[Vue warn]` nobody reads and
 * renders an inert unknown element, so the feature simply stops working in silence. Two such
 * bugs shipped this way: `<UiSonnerSonner />` (the toaster never mounted, so every success /
 * error toast in the app was dropped) and `<GroundGlass>` inside `GlassInput` (the glass slab
 * and its focus interaction never rendered). Both came from the same trap: Nuxt collapses a
 * filename that repeats its parent directory, so `ui/sonner/Sonner.vue` registers as `UiSonner`,
 * not `UiSonnerSonner`.
 *
 * `.nuxt/components.d.ts` is the authoritative registry — it is generated by `nuxt prepare`,
 * which runs from `postinstall` (so CI has it after `pnpm install`).
 */

/** Vitest resolves `root` to the directory holding `vitest.config.ts`, i.e. `gui/`. */
const GUI_ROOT = process.cwd()
const APP_DIR = join(GUI_ROOT, 'app')
const REGISTRY_FILE = join(GUI_ROOT, '.nuxt/components.d.ts')

if (!existsSync(REGISTRY_FILE))
  throw new Error(`Component registry missing at ${REGISTRY_FILE} — run \`pnpm exec nuxt prepare\` first.`)

/** Vue's own template elements — never in the Nuxt component registry, always resolvable. */
const VUE_BUILTINS = new Set([
  'Component',
  'KeepAlive',
  'Suspense',
  'Teleport',
  'Transition',
  'TransitionGroup',
])

/** Bounds: the tree is ~91 files, 4 levels deep — these sit far above it and cap a runaway walk. */
const DIRECTORY_DEPTH_MAX = 12
const VUE_FILES_MAX = 2000

/** Collect every `.vue` file under `directory`, depth-bounded and count-bounded. */
function collectVueFiles(directory: string, depth = 0, found: string[] = []): string[] {
  if (depth > DIRECTORY_DEPTH_MAX) return found
  for (const name of readdirSync(directory)) {
    if (found.length >= VUE_FILES_MAX) return found
    const path = join(directory, name)
    if (statSync(path).isDirectory()) collectVueFiles(path, depth + 1, found)
    else if (path.endsWith('.vue')) found.push(path)
  }
  return found
}

/** Names Nuxt auto-imports, read from the generated registry (`export const Foo: ...`). */
function readRegisteredNames(source: string): Set<string> {
  return new Set([...source.matchAll(/^export const (\w+):/gm)].map(match => match[1]!))
}

/**
 * Identifiers a single-file component binds itself: anything named in an `import ... from '...'`
 * clause (covering `Foo`, `{ Foo }` and `{ Bar as Foo }`, across line breaks) plus local
 * declarations. Over-collecting is safe here — the set is only ever used to *allow* a tag.
 */
function readLocalBindings(script: string): Set<string> {
  const names = new Set<string>()
  for (const statement of script.matchAll(/import\s+([\s\S]*?)\s+from\s*['"]/g))
    for (const identifier of statement[1]!.matchAll(/[A-Za-z_$][\w$]*/g)) names.add(identifier[0])
  for (const declaration of script.matchAll(/\b(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/g))
    names.add(declaration[1]!)
  return names
}

/** PascalCase tags opened anywhere in the file's `<template>` blocks. */
function readTemplateComponentTags(source: string): Set<string> {
  const template = [...source.matchAll(/<template>([\s\S]*?)<\/template>/g)]
    .map(block => block[1]!)
    .join('\n')
  return new Set([...template.matchAll(/<([A-Z][A-Za-z0-9]*)/g)].map(match => match[1]!))
}

const registrySource = readFileSync(REGISTRY_FILE, 'utf8')
const registeredNames = readRegisteredNames(registrySource)
const vueFiles = collectVueFiles(APP_DIR)

describe('component resolution', () => {
  // Negative space: a registry or file list that silently read as empty would make the
  // resolution test below pass vacuously, hiding exactly the bug it exists to catch.
  it('reads a non-empty component registry', () => {
    expect(registeredNames.size).toBeGreaterThan(0)
    expect(registeredNames.has('UiSonner')).toBe(true)
  })

  it('never treats an unregistered name as resolvable', () => {
    expect(registeredNames.has('UiSonnerSonner')).toBe(false)
    expect(registeredNames.has('GroundGlass')).toBe(false)
  })

  it('finds the single-file components to check', () => {
    expect(vueFiles.length).toBeGreaterThan(0)
    expect(vueFiles.length).toBeLessThanOrEqual(VUE_FILES_MAX)
  })

  it('resolves every component referenced in a template', () => {
    const unresolved: string[] = []
    for (const file of vueFiles) {
      const source = readFileSync(file, 'utf8')
      const script = [...source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)]
        .map(block => block[1]!)
        .join('\n')
      const localBindings = readLocalBindings(script)
      for (const tag of readTemplateComponentTags(source)) {
        if (registeredNames.has(tag) || VUE_BUILTINS.has(tag) || localBindings.has(tag)) continue
        unresolved.push(`${relative(GUI_ROOT, file).replace(/\\/g, '/')}: <${tag}>`)
      }
    }
    expect(unresolved).toEqual([])
  })
})
